In [7]:
import numpy as np
import time

In [8]:
size=100000
py_list=list(range(size))
start=time.time()
sq_list=[x**2  for x in py_list]
end=time.time();
print(f" python time={end-start} seconds")

 python time=0.03620147705078125 seconds


In [10]:
np_arr=np.array(py_list)
start=time.time()
sq_array=np_arr**2
end=time.time()
print(f"numpy takes ={end-start}seconds")

numpy takes =0.001238107681274414seconds


In [12]:
arr=np.array([1,2,3,4])
print(arr,type(arr),arr.shape)

[1 2 3 4] <class 'numpy.ndarray'> (4,)


In [13]:
array=np.array([[1,2,3],[7,8,9],[3,5,6]])
print(array)

[[1 2 3]
 [7 8 9]
 [3 5 6]]


In [15]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
